DATASET_NAME = "CIFAR10" # MNIST, CIFAR10 or POKEMON
SAVE_PATH = "results_" + DATASET_NAME + "/"

NB_EPOCH = 200

COMPLEXITY = 256
MINIBATCH_SIZE = 128
PACKING = 2
IMAGE_SIZE = 32
IMAGE_CHANNELS = 3

LEARNING_RATE = 0.0002

NB_DISCRIMINATOR_STEP = 1

NB_IMAGE_TO_GENERATE = 64
LATENT_INPUT = 100

REAL_LABEL_SMOOTHING = False
FAKE_LABEL_SMOOTHING = False

DROPOUT_PROB = 0.0

BETA1 = 0.5
BETA2 = 0.999

WEIGHTS_MEAN = 0.0
WEIGHTS_STD = 0.02