DATASET_NAME = "CIFAR10" # MNIST, CIFAR10 or POKEMON
SAVE_PATH = "results_" + DATASET_NAME + "/"

NB_EPOCH = 2

COMPLEXITY = 1
MINIBATCH_SIZE = 64
IMAGE_SIZE = 32
IMAGE_CHANNELS = 3
CODE_SIZE = 50

LEARNING_RATE = 0.002

NB_IMAGE_TO_GENERATE = 64

WEIGHTS_MEAN = 0.0
WEIGHTS_STD = 0.02